version: 2.1
orbs:
  shellcheck:     circleci/shellcheck@volatile
  docker-publish: circleci/docker@volatile
  snyk:           snyk/snyk@volatile  
#
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - shellcheck/check
      - docker-publish/publish:
          context: toonContext
          after_checkout:
            - run:
                name: Do this after checkout - set ENV variables.
                command: |
                  echo 'export TAG=0.1.$CIRCLE_BUILD_NUM DOCKER_PASSWORD=$DOCKER_PASS DOCKER_LOGIN=$DOCKER_USER' >> $BASH_ENV
          after_build:
            - snyk/scan:
               docker-image-name: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$TAG
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME    
          tag: '$TAG,latest'
          requires:
            - shellcheck/check